server:
  port: 18084
spring:
  application:
    name: mall-dubbo-provider
dubbo:
  application:
    name: mall-dubbo-provider
  registry:
    address: nacos://localhost:8848
    protocol:
        port: -1
        name: dubbo